# Generated by Django 5.2.1 on 2025-06-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=350)),
                ('descripcion', models.CharField(max_length=2500)),
                ('iEstado', models.IntegerField(default=1)),
            ],
        ),
    ]
